spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 로그인은 JWT 검증 제외
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        # inventory-service 라우팅
        - id: inventory-service
          uri: ${BACKEND_INVENTORY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/parts/**
          filters:
            - JwtAuthenticationFilter

        # order-service 라우팅
        - id: order-service
          uri: ${BACKEND_ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtAuthenticationFilter

server:
  port: 8080