spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # inventory-service 라우팅
        - id: inventory-service
          uri: ${BACKEND_INVENTORY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/parts/**
          filters:
            - StripPrefix=0

        # order-service 라우팅
        - id: order-service
          uri: ${BACKEND_ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0

server:
  port: 8080